version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            tests : 
            - not_null 

          - name: products_id
             - not null

          - name: qty

          - name: turnover
             - not null

          - name: purchase_cost
             - not null
          - name: margin